package com.MIBlog.dataobject;

import java.io.Serializable;
import java.util.Date;

public class Article implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.imgUrl
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.view
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private Integer view;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.top
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private Integer top;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.user_id
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type_id
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.status
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.gmt_create
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.gmt_modify
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.summary
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.imgUrl
     *
     * @return the value of article.imgUrl
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.imgUrl
     *
     * @param imgurl the value for article.imgUrl
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.view
     *
     * @return the value of article.view
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public Integer getView() {
        return view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.view
     *
     * @param view the value for article.view
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setView(Integer view) {
        this.view = view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.top
     *
     * @return the value of article.top
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.top
     *
     * @param top the value for article.top
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.user_id
     *
     * @return the value of article.user_id
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.user_id
     *
     * @param userId the value for article.user_id
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type_id
     *
     * @return the value of article.type_id
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.type_id
     *
     * @param typeId the value for article.type_id
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.status
     *
     * @return the value of article.status
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.status
     *
     * @param status the value for article.status
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.gmt_create
     *
     * @return the value of article.gmt_create
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.gmt_create
     *
     * @param gmtCreate the value for article.gmt_create
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.gmt_modify
     *
     * @return the value of article.gmt_modify
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.gmt_modify
     *
     * @param gmtModify the value for article.gmt_modify
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.summary
     *
     * @return the value of article.summary
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.summary
     *
     * @param summary the value for article.summary
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbg.generated Thu Apr 22 14:05:59 GMT+08:00 2021
     */
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        return "Article{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", imgurl='" + imgurl + '\'' +
                ", view=" + view +
                ", top=" + top +
                ", userId='" + userId + '\'' +
                ", typeId=" + typeId +
                ", status=" + status +
                ", gmtCreate=" + gmtCreate +
                ", gmtModify=" + gmtModify +
                ", summary='" + summary + '\'' +
                ", content='" + content + '\'' +
                '}';
    }
}
