package com.MIBlog.dataobject;

import java.io.Serializable;

public class Photo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.user_id
     *
     * @mbg.generated Thu Apr 22 17:33:11 GMT+08:00 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.imgUrl
     *
     * @mbg.generated Thu Apr 22 17:33:11 GMT+08:00 2021
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table photo
     *
     * @mbg.generated Thu Apr 22 17:33:11 GMT+08:00 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.user_id
     *
     * @return the value of photo.user_id
     *
     * @mbg.generated Thu Apr 22 17:33:11 GMT+08:00 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.user_id
     *
     * @param userId the value for photo.user_id
     *
     * @mbg.generated Thu Apr 22 17:33:11 GMT+08:00 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.imgUrl
     *
     * @return the value of photo.imgUrl
     *
     * @mbg.generated Thu Apr 22 17:33:11 GMT+08:00 2021
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.imgUrl
     *
     * @param imgurl the value for photo.imgUrl
     *
     * @mbg.generated Thu Apr 22 17:33:11 GMT+08:00 2021
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }
}