package com.MIBlog.dataobject;

import java.io.Serializable;

public class Thumbup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumbup.id
     *
     * @mbg.generated Mon Apr 26 16:05:06 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumbup.article_id
     *
     * @mbg.generated Mon Apr 26 16:05:06 GMT+08:00 2021
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumbup.user_id
     *
     * @mbg.generated Mon Apr 26 16:05:06 GMT+08:00 2021
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thumbup
     *
     * @mbg.generated Mon Apr 26 16:05:06 GMT+08:00 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumbup.id
     *
     * @return the value of thumbup.id
     *
     * @mbg.generated Mon Apr 26 16:05:06 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumbup.id
     *
     * @param id the value for thumbup.id
     *
     * @mbg.generated Mon Apr 26 16:05:06 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumbup.article_id
     *
     * @return the value of thumbup.article_id
     *
     * @mbg.generated Mon Apr 26 16:05:06 GMT+08:00 2021
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumbup.article_id
     *
     * @param articleId the value for thumbup.article_id
     *
     * @mbg.generated Mon Apr 26 16:05:06 GMT+08:00 2021
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumbup.user_id
     *
     * @return the value of thumbup.user_id
     *
     * @mbg.generated Mon Apr 26 16:05:06 GMT+08:00 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumbup.user_id
     *
     * @param userId the value for thumbup.user_id
     *
     * @mbg.generated Mon Apr 26 16:05:06 GMT+08:00 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}