package com.MIBlog.dataobject;

import java.io.Serializable;
import java.util.Date;

public class Type implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.id
     *
     * @mbg.generated Thu Apr 22 12:56:49 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_name
     *
     * @mbg.generated Thu Apr 22 12:56:49 GMT+08:00 2021
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.gmt_create
     *
     * @mbg.generated Thu Apr 22 12:56:49 GMT+08:00 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table type
     *
     * @mbg.generated Thu Apr 22 12:56:49 GMT+08:00 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.id
     *
     * @return the value of type.id
     *
     * @mbg.generated Thu Apr 22 12:56:49 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.id
     *
     * @param id the value for type.id
     *
     * @mbg.generated Thu Apr 22 12:56:49 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_name
     *
     * @return the value of type.type_name
     *
     * @mbg.generated Thu Apr 22 12:56:49 GMT+08:00 2021
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_name
     *
     * @param typeName the value for type.type_name
     *
     * @mbg.generated Thu Apr 22 12:56:49 GMT+08:00 2021
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.gmt_create
     *
     * @return the value of type.gmt_create
     *
     * @mbg.generated Thu Apr 22 12:56:49 GMT+08:00 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.gmt_create
     *
     * @param gmtCreate the value for type.gmt_create
     *
     * @mbg.generated Thu Apr 22 12:56:49 GMT+08:00 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}