package com.MIBlog.dao;

import com.MIBlog.dataobject.Menus;
import com.MIBlog.exmple.MenusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    long countByExample(MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    int deleteByExample(MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    int insert(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    int insertSelective(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    List<Menus> selectByExample(MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    Menus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Menus record, @Param("example") MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Menus record, @Param("example") MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Thu Apr 22 09:27:10 GMT+08:00 2021
     */
    int updateByPrimaryKey(Menus record);
}
